std_msgs/String component_name # equivalent to a ROS node name
std_msgs/String component_type # RTT component name (equivalent to node type)
std_msgs/String component_pkg # RTT or ROS package name, where the RTT component resides

std_msgs/String ns # ROS namespace of the real time component
Mapping[] mappings # ROS remappings that apply to the real time component

std_msgs/String topics_ignore_for_graph # topics which are not used during graph generation (can contain regex, this is applied after name resolution)
std_msgs/Bool is_first # Flag for real time components that are first in every iteration (e.g., hardware interface). This flag implies that there are no dependencies.
---
std_msgs/Bool success
